name: uefi-fw-tools
summary: A standalone version of fwupd to install newer firmware updates
description: |
  This is a tool that can be used to install firmware updates on devices
  not yet supported by the version of fwupd distributed with the OS.

grade: stable
confinement: strict
base: core18
adopt-info: fwupd

apps:
  udisksd:
    command: libexec/udisks2/udisksd
    daemon: simple
    slots: [udisks2]
    plugs:
      - hardware-observe
      - mount-observe
  dfu-tool:
    command: dfu-tool.wrapper
  dbxtool:
    command: dbxtool.wrapper
  fwupdtool:
    command: fwupdtool.wrapper
    completer:
      share/bash-completion/completions/fwupdtool
    plugs:
      - network
      - hardware-observe
      - tpm
  fwupd:
    command: fwupd.wrapper
    daemon: simple
    plugs:
      - hardware-observe
      - tpm
      - udisks2c
    slots: [fwupd]
  fwupdmgr:
    command: fwupdmgr.wrapper
    completer:
      share/bash-completion/completions/fwupdmgr
    plugs:
      - network
      - fwupdmgr
      - shutdown
  fwupdtpmevlog:
    command: fwupdtpmevlog.wrapper
  fwupdagent:
    command: fwupdagent.wrapper
    plugs: [network]

plugs:
  fwupdmgr:
    interface: fwupd
  udisks2c:
    interface: udisks2

slots:
  fwupd:
    interface: fwupd
  fwupd-data:
    content: fwupd-data
    interface: content
    write:
      - $SNAP_DATA
  udisks2:
    interface: udisks2

layout:
  /var/lib/udisks2:
    bind: $SNAP_DATA/var/lib/udisks2
  /etc/udisks2/udisks2.conf:
    bind-file: $SNAP/etc/udisks2/udisks2.conf
  /etc/libblockdev/conf.d:
    bind: $SNAP/etc/libblockdev/conf.d
  /usr/bin/gpg:
    bind-file: $SNAP/usr/bin/gpg

parts:
  udisks:
    source: https://github.com/storaged-project/udisks.git
    source-tag: udisks-2.7.6
    plugin: autotools
    override-pull: |
      snapcraftctl pull
      # apply patches from fwupd-snapcraft
      git am $SNAPCRAFT_PART_BUILD/../../../patches/udisks2/000*.patch
    configflags:
        - --enable-fhs-media
    install-via: destdir
    build-packages:
        - pkg-config
        - xsltproc
        - gtk-doc-tools
        - intltool
        - libglib2.0-dev
        - udev
        - gnome-common
        - libgudev-1.0-dev
        - libpolkit-gobject-1-dev
        - libpolkit-agent-1-dev
        - libacl1-dev
        - libgirepository1.0-dev
        - gobject-introspection
        - libatasmart-dev
        - libsystemd-dev
        - libmount-dev
        - libblockdev-dev
        - libblockdev-part-dev
        - libblockdev-loop-dev
        - libblockdev-swap-dev
        - libblockdev-mdraid-dev
        - libblockdev-fs-dev
        - libblockdev-crypto-dev
    stage-packages:
        - libacl1
        - libatasmart4
        - libglib2.0-0
        - libgudev-1.0-0
        - libpam-systemd
        - libpolkit-agent-1-0
        - libpolkit-gobject-1-0
        - parted
        - libmount1
        - libblockdev2
        - libblockdev-part2
        - libblockdev-loop2
        - libblockdev-swap2
        - libblockdev-mdraid2
        - libblockdev-fs2
        - libblockdev-crypto2
    filesets:
      licenses:
          - usr/share/doc/*/*copyright*
      binaries:
          - bin/udisksctl
          - libexec/udisks2/udisksd
    prime:
        - $binaries
        - $licenses
        - lib
        - -lib/pkgconfig
        - -lib/systemd
        - -lib/cgmanager
        - libexec
        - sbin
        - usr/lib/*/*.so*
  libefivar-dev:
    plugin: make
    source: https://github.com/rhboot/efivar.git
    source-type: git
    source-commit: f0d3ed17ef3b2bbdfdff4dde12ec0a82d1ccdd33
    build-packages:
      - libpopt-dev
    organize:
      usr/lib64: usr/lib/x86_64-linux-gnu
    override-build: |
      # apply patches from fwupd-snapcraft
      git am $SNAPCRAFT_PART_BUILD/../../../patches/efivar/000*.patch
      snapcraftctl build
  libefivar-fixpkgconfig:
    plugin: make
    source: libefivar-fixpkgconfig
    make-parameters:
      - SNAPCRAFT_STAGE=$SNAPCRAFT_STAGE
    after: [libefivar-dev]
  curl:
    plugin: dump
    source: https://curl.se/download/curl-7.73.0.tar.bz2
  tpm2-tss:
    plugin: autotools
    source: https://github.com/tpm2-software/tpm2-tss/releases/download/2.3.0/tpm2-tss-2.3.0.tar.gz
    configflags:
      - --disable-doxygen-doc
    prime:
      - -include
      - -bin
      - -share/man
      - -lib/pkgconfig
    build-packages:
      - libssl-dev
  nettle:
    plugin: autotools
    source: https://ftp.gnu.org/gnu/nettle/nettle-3.5.tar.gz
    build-packages:
      - libgmp-dev
    stage:
      - -share/info/dir
    prime:
      - -include
      - -bin
      - -share/man
      - -lib/pkgconfig
  gnutls:
    plugin: autotools
    source: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.12.tar.xz
    build-packages:
      - libtasn1-6-dev
      - libunistring-dev
      - libidn2-dev
      - libunbound-dev
      - libp11-kit-dev
    stage:
      - -share/info/dir
    prime:
      - -include
      - -bin
      - -share/man
      - -lib/pkgconfig
    after: [nettle]
  meson:
    plugin: python
    source: https://github.com/mesonbuild/meson/releases/download/0.54.0/meson-0.54.0.tar.gz
    build-packages:
      - ninja-build
      - python3-distutils-extra
    prime:
      - -bin
      - -etc
      - -lib
      - -share
      - -usr
  #needed for UEFI plugin to build UX labels
  build-introspection:
    plugin: nil
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-pil
    prime:
      - -etc
      - -usr
      - -lib
      - -var
  fwupd:
    plugin: meson
    meson-parameters: [--prefix=/,
                       -Dtests=false,
                       -Dbuild=all,
                       -Dgtkdoc=false,
                       -Dintrospection=false,
                       -Dman=false,
                       -Dpolkit=false,
                       -Dplugin_modem_manager=false,
                       -Dudevdir=$SNAPCRAFT_STAGE/lib/udev,
                       -Defi_os_dir=boot,
                       "-Dgusb:tests=false",
                       "-Dgusb:docs=false",
                       "-Dgusb:introspection=false",
                       "-Dgusb:vapi=false",
                       "-Dlibxmlb:gtkdoc=false",
                       "-Dlibxmlb:introspection=false",
                       "-Dlibjcat:man=false",
                       "-Dlibjcat:gtkdoc=false",
                       "-Dlibjcat:introspection=false",
                       "-Dlibjcat:tests=false"]
    source: https://github.com/fwupd/fwupd.git
    source-type: git
    source-tag: 1.5.4
    override-build: |
      # apply patches from fwupd-snapcraft
      git am $SNAPCRAFT_PART_BUILD/../../../patches/fwupd/000*.patch
      snapcraftctl build
      echo $(git describe HEAD --always) > $SNAPCRAFT_STAGE/version
      # TODO: don't use hardcoded
      UEFI_FW_TOOLS=1.6.2
      FWUPD=1.5.4
      VERSION=$UEFI_FW_TOOLS-$FWUPD+git$(git rev-parse --short HEAD)
      snapcraftctl set-version $VERSION
    build-packages:
      - bash-completion
      - gcab
      - gnu-efi
      - libarchive-dev
      - libcairo-dev
      - libelf-dev
      - libftdi1-dev
      - libgudev-1.0-dev
      - libgusb-dev
      - libgcab-dev
      - libglib2.0-dev
      - libgpgme11-dev
      - libjson-glib-dev
      - libpango1.0-dev
      - libpci-dev
      - libpolkit-gobject-1-dev
      - libsmbios-dev
      - libsqlite3-dev
      - libsystemd-dev
      - locales
      - pkg-config
      - systemd
      - uuid-dev
      - libcurl4-gnutls-dev
    stage-packages:
      - libgcab-1.0-0
      - libarchive13
      - libassuan0
      - liblcms2-2
      - libelf1
      - libgusb2
      - libusb-1.0-0
      - libgudev-1.0-0
      - libgpgme11
      - libjson-glib-1.0-0
      - libpolkit-gobject-1-0
      - libsmbios-c2
      - glib-networking
      - libglib2.0-bin
      - libcurl3-gnutls
    prime:
      # we explicitly don't want /usr/bin/gpgconf
      # this will cause gpgme to error finding it
      # but that also avoids trying to use non-existent
      # /usr/bin/gpg2
      - -usr/bin
      - -usr/sbin
      - -usr/share/man
      - -usr/share/GConf
      - -etc/X11
      - -etc/ldap
      - -etc/logcheck
      - -usr/lib/dconf
      - -usr/lib/gcc
      - -usr/lib/glib-networking
      - -usr/lib/gnupg2
      - -usr/lib/sasl2
      - -usr/lib/systemd
      - -usr/lib/*/audit
      - -usr/share/glib-2.0/schemas
      - -usr/share/X11
      - -include
      - -lib/udev
      - -lib/*/pkgconfig
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/installed-tests
      - -usr/share/polkit-1
      - -usr/share/vala
      - -usr/share/doc
      - -usr/share/gnupg2
      - -usr/share/info
      - -usr/share/gir-1.0
      - -usr/share/upstart
      - -usr/lib/*/pkgconfig
      # we don't want system gnutls leaking in
      - -usr/lib/*/libgnutls*
    after: [libefivar-fixpkgconfig, meson, build-introspection, tpm2-tss, gnutls, curl]
  #fetch the latest version of the signed bootloader
  #this might not match our fwupdx64.efi, but it's better than nothing
  fwup-efi-signed:
    build-packages:
      - python3-apt
    plugin: make
    source: .
    override-build: |
      cp -r $SNAPCRAFT_PROJECT_DIR/parts/fwupd/src/contrib/snap/fwup-efi-signed/* .
      snapcraftctl build
    after: [fwupd]
  fix-bash-completion:
    plugin: make
    source: .
    override-build: |
      cp -r $SNAPCRAFT_PROJECT_DIR/parts/fwupd/src/contrib/snap/fix-bash-completion/* .
      snapcraftctl build
    after: [fwupd]
  activate-shutdown:
    plugin: make
    source: .
    override-build: |
      cp -r $SNAPCRAFT_PROJECT_DIR/parts/fwupd/src/contrib/snap/activate-shutdown/* .
      snapcraftctl build
    after: [fwupd]
  update-mime:
    plugin: make
    source: .
    override-build: |
      cp -r $SNAPCRAFT_PROJECT_DIR/parts/fwupd/src/contrib/snap/update-mime/* .
      snapcraftctl build
    stage-packages:
      - shared-mime-info
      - gsettings-desktop-schemas
      - libxml2
    prime:
      - -usr/bin
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/pkgconfig
      - -usr/share/GConf
    after: [fwupd]
  fwupd-wrappers:
    plugin: dump
    source: .
    override-build: |
      cp -r $SNAPCRAFT_PROJECT_DIR/parts/fwupd/src/contrib/snap/*.wrapper .
      cp -r $SNAPCRAFT_PROJECT_DIR/parts/fwupd/src/contrib/snap/fwupd-command .
      snapcraftctl build
    stage:
      - dfu-tool.wrapper
      - dbxtool.wrapper
      - fwupd-command
      - fwupdtool.wrapper
      - fwupd.wrapper
      - fwupdmgr.wrapper
      - fwupdtpmevlog.wrapper
      - fwupdagent.wrapper
    after: [update-mime]
  gpg:
    plugin: nil
    stage-packages:
      - gpg
    prime:
      - -usr/bin/gpgconf
      - -usr/bin/gpg-connect-agent
      - -usr/share/doc
      - -usr/share/man
  fwupd-uefi-conf:
    plugin: nil
    override-prime: |
      sed -i 's|#FallbacktoRemovablePath=false|FallbacktoRemovablePath=true|' etc/fwupd/uefi.conf
